package main

import (
	"strings"
	"testing"
)

func TestValidateCapabilitiesUnknownName(t *testing.T) {
	err := validateCapabilities(map[string]bool{"warp-drive": false})
	if err == nil || !strings.Contains(err.Error(), `unknown capability "warp-drive"`) {
		t.Fatalf("want unknown-capability error, got %v", err)
	}
}

func TestValidateCapabilitiesKnownIsAccepted(t *testing.T) {
	if err := validateCapabilities(map[string]bool{"ble": false}); err != nil {
		t.Fatalf("ble off must be accepted: %v", err)
	}
	if err := validateCapabilities(map[string]bool{"ble": true}); err != nil {
		t.Fatalf("ble on (no-op) must be accepted: %v", err)
	}
}

func TestDisabledCapabilitiesSkipsEnabledAndSorts(t *testing.T) {
	disabled := disabledCapabilities(map[string]bool{"ble": false})
	if len(disabled) != 1 || disabled[0].name != "ble" {
		t.Fatalf("want [ble] disabled, got %v", disabled)
	}
	if got := disabledCapabilities(map[string]bool{"ble": true}); len(got) != 0 {
		t.Fatalf("an enabled capability must not appear as disabled, got %v", got)
	}
}

func TestGeneratedCompositionH(t *testing.T) {
	got := generatedCompositionH(disabledCapabilities(map[string]bool{"ble": false}))
	want := "/* Generated by frothy build. Do not edit. */\n" +
		"#define FR_FEATURE_BLE 0\n"
	if got != want {
		t.Fatalf("composition.h mismatch:\n%q\nwant\n%q", got, want)
	}
}

func TestGeneratedCompositionSdkconfig(t *testing.T) {
	got := generatedCompositionSdkconfig(disabledCapabilities(map[string]bool{"ble": false}))
	want := "# Generated by frothy build. Do not edit.\nCONFIG_BT_ENABLED=n\n"
	if got != want {
		t.Fatalf("composition sdkconfig mismatch:\n%q\nwant\n%q", got, want)
	}
}
