package main

import (
	"fmt"
	"sort"
	"strings"
)

// The offered capabilities are the gated features a custom firmware
// composition may turn off. Public semantics live here — the name and the
// off-bundle's top-level effects (the composition.h defines and sdkconfig
// lines applied when the capability is disabled). The profile still owns the
// concrete realization values that apply when the capability is on. v1 offers
// one bundle; net follows after its own sdkconfig audit.
type capability struct {
	name         string
	offDefines   []string
	offSdkconfig []string
}

var offeredCapabilities = []capability{
	{
		name:         "ble",
		offDefines:   []string{"#define FR_FEATURE_BLE 0"},
		offSdkconfig: []string{"CONFIG_BT_ENABLED=n"},
	},
}

// knownCapabilities is the set of names a library may name in `requires`. It
// is a superset of the offered names: always-on features like cells and i2c
// are legitimate requirements but are not composition toggles, so they never
// appear in offeredCapabilities. A library requiring an always-on capability
// is always satisfied; a library requiring an offered one is satisfied unless
// the composition disables it.
var knownCapabilities = func() map[string]bool {
	known := map[string]bool{
		// Always-on requirement targets (not offerable toggles).
		"cells": true,
		"text":  true,
		"i2c":   true,
		"pwm":   true,
		"uart":  true,
	}
	for _, c := range offeredCapabilities {
		known[c.name] = true
	}
	return known
}()

func isKnownCapability(name string) bool { return knownCapabilities[name] }

func capabilityByName(name string) (capability, bool) {
	for _, c := range offeredCapabilities {
		if c.name == name {
			return c, true
		}
	}
	return capability{}, false
}

// validateCapabilities rejects any name that is not an offered capability.
// Non-boolean values are already rejected by TOML decoding into
// map[string]bool. An explicit true is a no-op: the capability stays on.
func validateCapabilities(selected map[string]bool) error {
	for name := range selected {
		if _, ok := capabilityByName(name); !ok {
			return fmt.Errorf("unknown capability %q; offered: %s", name, offeredCapabilityNames())
		}
	}
	return nil
}

// disabledCapabilities returns the offered capabilities set to false, sorted
// by name so generated files are stable across runs.
func disabledCapabilities(selected map[string]bool) []capability {
	var out []capability
	for name, enabled := range selected {
		if enabled {
			continue
		}
		if c, ok := capabilityByName(name); ok {
			out = append(out, c)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

func generatedCompositionH(disabled []capability) string {
	var b strings.Builder
	b.WriteString("/* Generated by frothy build. Do not edit. */\n")
	for _, c := range disabled {
		for _, line := range c.offDefines {
			b.WriteString(line)
			b.WriteByte('\n')
		}
	}
	return b.String()
}

func generatedCompositionSdkconfig(disabled []capability) string {
	var b strings.Builder
	b.WriteString("# Generated by frothy build. Do not edit.\n")
	for _, c := range disabled {
		for _, line := range c.offSdkconfig {
			b.WriteString(line)
			b.WriteByte('\n')
		}
	}
	return b.String()
}

func offeredCapabilityNames() string {
	names := make([]string, 0, len(offeredCapabilities))
	for _, c := range offeredCapabilities {
		names = append(names, c.name)
	}
	sort.Strings(names)
	return strings.Join(names, ", ")
}
