package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestGeneratedLibsCMakeEmpty(t *testing.T) {
	got := generatedLibsCMake(nil)
	want := "# Generated by frothy build. Do not edit.\n" +
		"set(FROTHY_LIB_EXT_SOURCES)\n" +
		"set(FROTHY_LIB_EXT_INCLUDE_DIRS)\n"
	if got != want {
		t.Fatalf("empty libs.cmake mismatch:\nwant:\n%s\n\ngot:\n%s", want, got)
	}
}

func TestGeneratedLibsCMakeIgnoresPureModulesLibs(t *testing.T) {
	libs := []resolvedLibrary{
		{name: "test-pure", path: "/proj/libs/test-pure"},
	}
	got := generatedLibsCMake(libs)
	want := "# Generated by frothy build. Do not edit.\n" +
		"set(FROTHY_LIB_EXT_SOURCES)\n" +
		"set(FROTHY_LIB_EXT_INCLUDE_DIRS)\n"
	if got != want {
		t.Fatalf("pure-modules lib should produce empty lists; got:\n%s", got)
	}
}

func TestGeneratedLibsCMakeAbsolutifiesAndSorts(t *testing.T) {
	libs := []resolvedLibrary{
		{
			name: "neopixel",
			path: "/proj/libs/neopixel",
			extension: &libraryExtension{
				sources:     []string{"native/neopixel.c"},
				includeDirs: []string{"native/include"},
			},
		},
		{
			name: "stage",
			path: "/proj/libs/stage",
			extension: &libraryExtension{
				sources: []string{"native/stage.c", "native/dim.c"},
			},
		},
	}
	got := generatedLibsCMake(libs)
	want := "# Generated by frothy build. Do not edit.\n" +
		"set(FROTHY_LIB_EXT_SOURCES\n" +
		"  /proj/libs/neopixel/native/neopixel.c\n" +
		"  /proj/libs/stage/native/dim.c\n" +
		"  /proj/libs/stage/native/stage.c\n" +
		")\n" +
		"set(FROTHY_LIB_EXT_INCLUDE_DIRS\n" +
		"  /proj/libs/neopixel/native/include\n" +
		")\n"
	if got != want {
		t.Fatalf("libs.cmake mismatch:\nwant:\n%s\n\ngot:\n%s", want, got)
	}
}

func TestGeneratedLibNativesCEmpty(t *testing.T) {
	got, err := generatedLibNativesC([]resolvedLibrary{{name: "test-pure", path: "/proj/libs/test-pure"}})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := "/* Generated by frothy build. Do not edit. */\n" +
		"#include \"lib_native.h\"\n\n" +
		"/* No library natives. */\n" +
		"const fr_lib_native_def_t fr_lib_natives[1] = {{0}};\n" +
		"const uint16_t fr_lib_natives_count = 0;\n"
	if got != want {
		t.Fatalf("empty lib_natives.c mismatch:\nwant:\n%s\n\ngot:\n%s", want, got)
	}
	for _, wantPart := range []string{
		"#include \"lib_native.h\"",
		"fr_lib_natives[1]",
		"fr_lib_natives_count = 0",
	} {
		if !strings.Contains(got, wantPart) {
			t.Fatalf("empty lib_natives.c missing %q:\n%s", wantPart, got)
		}
	}
	assertGeneratedCCompiles(t, "lib_natives.c", got)
}

func TestGeneratedLibNativesCMixed(t *testing.T) {
	libs := []resolvedLibrary{
		{
			name: "neopixel",
			path: "/proj/libs/neopixel",
			natives: []libraryNative{
				{name: "neopixel.show", arity: 1, cFunction: "fr_lib_neopixel_show"},
				{name: "neopixel.close", arity: 1, cFunction: "fr_lib_neopixel_close"},
			},
		},
		{
			name: "stage",
			path: "/proj/libs/stage",
			natives: []libraryNative{
				{name: "stage.dim", arity: 2, cFunction: "fr_lib_stage_dim"},
			},
		},
	}
	got, err := generatedLibNativesC(libs)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := "/* Generated by frothy build. Do not edit. */\n" +
		"#include \"lib_native.h\"\n\n" +
		"extern fr_err_t fr_lib_neopixel_show(fr_runtime_t *runtime, const fr_tagged_t *args, uint8_t arg_count, fr_tagged_t *out);\n" +
		"extern fr_err_t fr_lib_neopixel_close(fr_runtime_t *runtime, const fr_tagged_t *args, uint8_t arg_count, fr_tagged_t *out);\n" +
		"extern fr_err_t fr_lib_stage_dim(fr_runtime_t *runtime, const fr_tagged_t *args, uint8_t arg_count, fr_tagged_t *out);\n" +
		"\n" +
		"const fr_lib_native_def_t fr_lib_natives[] = {\n" +
		"  {\"neopixel.show\", fr_lib_neopixel_show, 1},\n" +
		"  {\"neopixel.close\", fr_lib_neopixel_close, 1},\n" +
		"  {\"stage.dim\", fr_lib_stage_dim, 2},\n" +
		"};\n" +
		"const uint16_t fr_lib_natives_count = 3;\n"
	if got != want {
		t.Fatalf("lib_natives.c mismatch:\nwant:\n%s\n\ngot:\n%s", want, got)
	}
}

func TestGeneratedLibNativesCRejectsBadInput(t *testing.T) {
	cases := []struct {
		desc   string
		native libraryNative
	}{
		{"empty name", libraryNative{name: "", arity: 0, cFunction: "fr_x"}},
		{"empty c_function", libraryNative{name: "x.y", arity: 0, cFunction: ""}},
		{"quote in name", libraryNative{name: "bad\"name", arity: 0, cFunction: "fr_x"}},
		{"backslash in name", libraryNative{name: "bad\\name", arity: 0, cFunction: "fr_x"}},
		{"newline in name", libraryNative{name: "bad\nname", arity: 0, cFunction: "fr_x"}},
		{"tab in name", libraryNative{name: "bad\tname", arity: 0, cFunction: "fr_x"}},
		{"null in name", libraryNative{name: "bad\x00name", arity: 0, cFunction: "fr_x"}},
		{"del in name", libraryNative{name: "bad\x7fname", arity: 0, cFunction: "fr_x"}},
		{"space in name", libraryNative{name: "bad name", arity: 0, cFunction: "fr_x"}},
		{"slash in name", libraryNative{name: "bad/name", arity: 0, cFunction: "fr_x"}},
		{"non-ascii in name", libraryNative{name: "näme", arity: 0, cFunction: "fr_x"}},
		{"leading digit in name", libraryNative{name: "1.show", arity: 0, cFunction: "fr_x"}},
		{"leading hyphen in name", libraryNative{name: "-show", arity: 0, cFunction: "fr_x"}},
		{"c_function with dot", libraryNative{name: "x.y", arity: 0, cFunction: "fr.x"}},
		{"c_function starts with digit", libraryNative{name: "x.y", arity: 0, cFunction: "1fr"}},
	}
	for _, c := range cases {
		t.Run(c.desc, func(t *testing.T) {
			_, err := generatedLibNativesC([]resolvedLibrary{{natives: []libraryNative{c.native}}})
			if err == nil {
				t.Fatalf("expected error for %s, got none", c.desc)
			}
		})
	}
}

func TestValidNativeName(t *testing.T) {
	cases := map[string]bool{
		"":                false,
		"x":               true,
		"neopixel.show":   true,
		"uart.write-byte": true,
		"with_underscore": true,
		"1leading":        false,
		"-leading":        false,
		"bad name":        false,
		"bad\nname":       false,
		"bad\"name":       false,
		"bad\\name":       false,
		"bad/name":        false,
		"bad+name":        false,
		"bad:name":        false,
	}
	for input, want := range cases {
		if got := validNativeName(input); got != want {
			t.Errorf("validNativeName(%q) = %v, want %v", input, got, want)
		}
	}
}

func TestValidCIdentifier(t *testing.T) {
	cases := map[string]bool{
		"":                false,
		"_":               true,
		"x":               true,
		"X":               true,
		"x1":              true,
		"1x":              false,
		"fr_lib_show":     true,
		"fr.lib.show":     false,
		"fr-lib-show":     false,
		"fr lib show":     false,
		"fr_lib_show_123": true,
	}
	for input, want := range cases {
		if got := validCIdentifier(input); got != want {
			t.Errorf("validCIdentifier(%q) = %v, want %v", input, got, want)
		}
	}
}

func assertGeneratedCCompiles(t *testing.T, name, source string) {
	t.Helper()
	cc, err := exec.LookPath("cc")
	if err != nil {
		t.Skip("cc not available")
	}
	dir := t.TempDir()
	srcPath := filepath.Join(dir, name)
	if err := os.WriteFile(srcPath, []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(cc,
		"-std=c99", "-Wall", "-Wextra", "-Werror", "-pedantic",
		"-I", filepath.Join("..", "..", "src"),
		"-I", filepath.Join("..", "..", "profiles"),
		"-c", srcPath,
		"-o", filepath.Join(dir, "out.o"),
	)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("compile generated %s: %v\n%s", name, err, string(out))
	}
}
