package main

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// SPEC D10 + D13. frothy build emits two files per target build dir:
// libs.cmake (extension sources + include dirs the per-target CMake
// include()s) and lib_natives.c (extern decls + strong override of the
// fr_lib_natives table the kernel's weak default leaves empty).
//
// Pure data in, file contents out. Manifest parsing and disk I/O sit
// on either side of these functions; tests exercise them directly.

type libraryExtension struct {
	sources     []string
	includeDirs []string
}

type libraryNative struct {
	name      string
	arity     uint8
	cFunction string
}

type resolvedLibrary struct {
	name      string
	path      string
	extension *libraryExtension
	natives   []libraryNative
}

// Sources and include dirs are sorted so reruns don't churn the file
// on no-op rebuilds. Native order is preserved because D4's
// last-write-wins relies on it.
func generatedLibsCMake(libs []resolvedLibrary) string {
	var sources []string
	var includes []string
	for _, lib := range libs {
		if lib.extension == nil {
			continue
		}
		for _, src := range lib.extension.sources {
			sources = append(sources, filepath.Join(lib.path, src))
		}
		for _, inc := range lib.extension.includeDirs {
			includes = append(includes, filepath.Join(lib.path, inc))
		}
	}
	sort.Strings(sources)
	sort.Strings(includes)

	var b strings.Builder
	b.WriteString("# Generated by frothy build. Do not edit.\n")
	writeCMakeList(&b, "FROTHY_LIB_EXT_SOURCES", sources)
	writeCMakeList(&b, "FROTHY_LIB_EXT_INCLUDE_DIRS", includes)
	return b.String()
}

func writeCMakeList(b *strings.Builder, name string, items []string) {
	if len(items) == 0 {
		fmt.Fprintf(b, "set(%s)\n", name)
		return
	}
	fmt.Fprintf(b, "set(%s\n", name)
	for _, item := range items {
		fmt.Fprintf(b, "  %s\n", item)
	}
	b.WriteString(")\n")
}

// Empty input keeps the strong override absent so lib_native.c's weak
// fr_lib_natives[1] = {{0}} / count = 0 wins. The build still compiles
// the file — it just contributes nothing.
func generatedLibNativesC(libs []resolvedLibrary) (string, error) {
	var natives []libraryNative
	for _, lib := range libs {
		natives = append(natives, lib.natives...)
	}
	for _, n := range natives {
		if err := validateNative(n); err != nil {
			return "", err
		}
	}

	var b strings.Builder
	b.WriteString("/* Generated by frothy build. Do not edit. */\n")
	if len(natives) == 0 {
		b.WriteString("/* No library natives. */\n")
		return b.String(), nil
	}
	b.WriteString("#include \"lib_native.h\"\n\n")
	for _, n := range natives {
		fmt.Fprintf(&b,
			"extern fr_err_t %s(fr_runtime_t *runtime, const fr_tagged_t *args, uint8_t arg_count, fr_tagged_t *out);\n",
			n.cFunction)
	}
	b.WriteString("\nconst fr_lib_native_def_t fr_lib_natives[] = {\n")
	for _, n := range natives {
		fmt.Fprintf(&b, "  {\"%s\", %s, %d},\n", n.name, n.cFunction, n.arity)
	}
	b.WriteString("};\n")
	fmt.Fprintf(&b, "const uint16_t fr_lib_natives_count = %d;\n", len(natives))
	return b.String(), nil
}

func validateNative(n libraryNative) error {
	if n.name == "" {
		return fmt.Errorf("native has empty name")
	}
	if n.cFunction == "" {
		return fmt.Errorf("native %s has empty c_function", n.name)
	}
	if !validNativeName(n.name) {
		return fmt.Errorf("native name %q is not a source word", n.name)
	}
	if !validCIdentifier(n.cFunction) {
		return fmt.Errorf("native %s c_function %q is not a C identifier", n.name, n.cFunction)
	}
	return nil
}

// D4: native names look like <libname>.<word> — the kernel parser
// tokenizes them as a single FR_TOKEN_NAME. This is a strict subset of
// what the parser accepts, chosen to (a) cover every existing native
// (gpio.read, uart.write-byte, neopixel.show) and (b) shut out anything
// that would distort the generated C string: control bytes, quotes,
// backslashes, whitespace, parser-terminator punctuation. Leading `-`
// is refused because parse.c:302-315 consumes it as FR_TOKEN_MINUS, so
// a name starting with `-` would never tokenize back to one name.
func validNativeName(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= 'A' && r <= 'Z':
		case r == '.' || r == '_':
		case i > 0 && r == '-':
		case i > 0 && r >= '0' && r <= '9':
		default:
			return false
		}
	}
	return true
}

func validCIdentifier(s string) bool {
	for i, r := range s {
		switch {
		case r == '_':
		case r >= 'a' && r <= 'z':
		case r >= 'A' && r <= 'Z':
		case i > 0 && r >= '0' && r <= '9':
		default:
			return false
		}
	}
	return s != ""
}
