// GENERATED by tools/gen-examples-manifest.mjs from examples/*.fr.
// Do not edit by hand; run `make examples-manifest`.
export interface FrothyExample {
  name: string;
  title: string;
  blurb: string;
  tags: string[];
  source: string;
}
export const FROTHY_EXAMPLES: readonly FrothyExample[] = [
  {
    "name": "01-hello",
    "title": "Hello",
    "blurb": "Starts with values, arithmetic, grouping, and a printed line.",
    "tags": [
      "host"
    ],
    "source": "-- Hello\n-- Starts with values, arithmetic, grouping, and a printed line.\n-- @tag host\n\n-7 + 50 -- => 43\n2 * 3 + 4 -- => 10\n(2 + 3) * 4 -- => 20\nprint: \"hello\"\n"
  },
  {
    "name": "02-words",
    "title": "Words",
    "blurb": "Defines words, calls zero-argument words with a colon, and uses recursion.",
    "tags": [
      "host"
    ],
    "source": "-- Words\n-- Defines words, calls zero-argument words with a colon, and uses recursion.\n-- @tag host\n\nto double with n [ n * 2 ]\ndouble: 21 -- => 42\nto greet [ print: \"hi\" ]\ngreet:\nto fib with n [ if n < 2 [ n ] else [ fib: n - 1 + fib: n - 2 ] ]\nfib: 10 -- => 55\nsee double\n"
  },
  {
    "name": "03-truthiness",
    "title": "Truthiness",
    "blurb": "Shows if/else, loose truthiness, and boolean operators.",
    "tags": [
      "host"
    ],
    "source": "-- Truthiness\n-- Shows if/else, loose truthiness, and boolean operators.\n-- @tag host\n\nif 5 [ 1 ] else [ 2 ] -- => 1\nif nil [ 1 ] else [ 2 ] -- => 2\nif 0 [ 1 ] else [ 2 ] -- => 2\nnot nil -- => true\n1 < 2 and 3 < 4 -- => true\n1 > 2 or 3 < 4 -- => true\nnot false -- => true\n"
  },
  {
    "name": "04-loops",
    "title": "Loops",
    "blurb": "Uses locals with here, mutation with set, repeat indexes, and while loops.",
    "tags": [
      "host"
    ],
    "source": "-- Loops\n-- Uses locals with here, mutation with set, repeat indexes, and while loops.\n-- @tag host\n\nto sum-to with n [ here t is 0; repeat n as i [ set t to t + i ]; t ]\nsum-to: 10 -- => 45\nto count-down with n [ here x is n; while x > 0 [ set x to x - 1 ]; x ]\ncount-down: 9 -- => 0\n"
  },
  {
    "name": "05-cells",
    "title": "Cells",
    "blurb": "Creates a fixed-size mutable array, writes cells, and reads them back.",
    "tags": [
      "host"
    ],
    "source": "-- Cells\n-- Creates a fixed-size mutable array, writes cells, and reads them back.\n-- @tag host\n\nreadings is cells(3)\nset readings[0] to 11\nset readings[1] to 22\nset readings[2] to 33\nreadings[0] + readings[1] -- => 33\nreadings[0] + readings[1] + readings[2] -- => 66\n"
  },
  {
    "name": "06-records",
    "title": "Records",
    "blurb": "Declares a record shape, constructs a record, and reads and writes fields.",
    "tags": [
      "host"
    ],
    "source": "-- Records\n-- Declares a record shape, constructs a record, and reads and writes fields.\n-- @tag host\n\nrecord pt [ x, y ]\np is pt: 3, 4\np -> x + p -> y -- => 7\nset p -> x to 30\np -> x -- => 30\n"
  },
  {
    "name": "07-attempt-rescue",
    "title": "Attempt Rescue",
    "blurb": "Handles a failed expression and reads error.code inside rescue.",
    "tags": [
      "host"
    ],
    "source": "-- Attempt Rescue\n-- Handles a failed expression and reads error.code inside rescue.\n-- @tag host\n\nto safe-div with a, b [ attempt [ a / b ] rescue [ error.code ] ]\nsafe-div: 10, 2 -- => 5\nsafe-div: 10, 0 -- => 3\n"
  },
  {
    "name": "08-blink",
    "title": "Blink",
    "blurb": "Uses GPIO and LED words; host runs the same calls against stubs.",
    "tags": [
      "host",
      "device"
    ],
    "source": "-- Blink\n-- Uses GPIO and LED words; host runs the same calls against stubs.\n-- @tag host device\n\ngpio.output: 2\ngpio.write: 2, 0\ngpio.toggle: 2\ngpio.read: 2 -- => 1\nrepeat 2 [ led.on:; led.off: ]\ngpio.toggle: $led_builtin\ngpio.read: $led_builtin -- => 1\n"
  },
  {
    "name": "09-sensor",
    "title": "Sensor",
    "blurb": "Reads an ADC pin and converts ranges. Real readings are environmental, so only the pure map math is asserted; the adc lines just show a live value.",
    "tags": [
      "host",
      "device"
    ],
    "source": "-- Sensor\n-- Reads an ADC pin and converts ranges. Real readings are environmental, so\n-- only the pure map math is asserted; the adc lines just show a live value.\n-- @tag host device\n\nadc.read: 34\nadc.percent: 34\nmap: 50, 0, 100, 0, 1023 -- => 511\n"
  },
  {
    "name": "10-events",
    "title": "Events",
    "blurb": "Registers timers from inside definition bodies for device-side async output.",
    "tags": [
      "device"
    ],
    "source": "-- Events\n-- Registers timers from inside definition bodies for device-side async output.\n-- @tag device\n\nto start-ticking [ every 1000 [ print: \"tick\" ] ]\nto blink-later [ after 500 [ led.toggle: ] ]\nstart-ticking:\nblink-later:\n"
  },
  {
    "name": "11-persistence",
    "title": "Persistence",
    "blurb": "Saves cells and words, restores them, and reads the saved values back.",
    "tags": [
      "host"
    ],
    "source": "-- Persistence\n-- Saves cells and words, restores them, and reads the saved values back.\n-- @tag host\n\ntally is cells(1)\nset tally[0] to 7\nto tally-plus with n [ tally[0] + n ]\nsave\nclear\nrestore\ntally[0] -- => 7\ntally-plus: 5 -- => 12\n"
  }
];
