#pragma once

#define FR_BOARD_UART_BAUD 115200UL

#define FR_BOARD_LED_BUILTIN 13u
#define FR_BOARD_LED_DDR DDRB
#define FR_BOARD_LED_PORT PORTB
#define FR_BOARD_LED_BIT PB5
#define FR_BOARD_LED_ACTIVE_HIGH 1
